# StarLoco - Login (local)
system.server.exchange.ip 127.0.0.1
system.server.exchange.port 666
system.server.exchange.key ChangeMeYn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=

system.server.login.port 450
system.server.login.version 1.39.8e

database.login.host 127.0.0.1
database.login.port 3306
database.login.user root
database.login.pass 
database.login.name starloco_login
